### ISSUE TITLE
Bug with interpreter not found.

### ISSUE THREAD

**Issue by smachs** [ddmitov/elephant-harness-demo-electron#1]
Even with the file in the folder the interpreter returns error saying that test file was not found.
![php1](https://user-images.githubusercontent.com/6456734/27726061-43c91c6e-5d4f-11e7-8b4a-81ddc2fe573d.png)

Code reference:
![php2](https://user-images.githubusercontent.com/6456734/27726126-7fac40b2-5d4f-11e7-9d06-27a5b03cf71f.png)

File into folder.
![php3](https://user-images.githubusercontent.com/6456734/27726160-a24c7da8-5d4f-11e7-943d-2109d3db60c6.png)

**Comment by ddmitov** [comment]
Dear Gabriel,

elephant-harness requires a full path to a PHP interpeter or a PHP interpreter on PATH.
elephant-harness-demo-electron is made to work with only PHP interpreter on PATH because a full path to a PHP interpreter on a user machine can not be reliably guessed.

Your problem is that for some reason no PHP interpreter ('php-cgi' binary) is available on your PATH and no full path to a PHP interpreter is manually inserted in the code.

You can still use elephant-harness-demo-electron without a PHP interpreter on PATH, but in your elephant-harness object you have to give the full file path to a working 'php-cgi' binary like that:

index.js lines 23 - 24:
var versionScriptObject = {};
versionScriptObject.interpreter = '/usr/bin/php-cgi'; // Put php-cgi full path here.

The line you have highlighted in one of your screenshots is responsible for finding the PHP file that is going to be executed and this code does not and can not find a PHP interpreter.

With all my best wishes,
Dimitar

**Comment by smachs** [comment]
Ok, thanks :]
